language: csharp
dotnet: 2.1.500
matrix:
    include:
        - os: linux
          mono: 5.16.0
        - os: windows
          mono: none
env:
  - CG_CONTEXT_SHOW_BACKTRACE=1
before_script:
  - export FrameworkPathOverride=/usr/lib/mono/4.5/
script:
  - dotnet test -c Release
  - dotnet build -c Release
  - dotnet pack -c Release -o ./artifacts
